settings:
    channel:
        title: My Feed
        link: https://basyura.org/rssgen/feed.xml
        description: オレのフィード
    limit: 20

feeds:
    - title: B'z NEWS
      url: https://bz-vermillion.com/news/
      xpath: ul.news_list
    - title: L'arc-en-Ciel NEWS
      url: https://larc-en-ciel.com/s/n137/news/list
      xpath: .news-index
